// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShipmentTrackingAPI.Data;
using ShipmentTrackingAPI.Models.Enums;

#nullable disable

namespace ShipmentTrackingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619072347_AddTotalCostToShipment")]
    partial class AddTotalCostToShipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "address_type", new[] { "Pickup", "Dropoff" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "address_type", "address_type", new[] { "pickup", "dropoff" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "driver_account_status", new[] { "PendingApproval", "Active", "Suspended", "Deleted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "driver_account_status", "driver_account_status", new[] { "pending_approval", "active", "suspended", "deleted" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "driver_op_status", new[] { "Available", "InTransit", "Offline" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "driver_op_status", "driver_op_status", new[] { "available", "in_transit", "offline" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "otp_type", new[] { "Pickup", "Delivery" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "otp_type", "otp_type", new[] { "pickup", "delivery" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "shipment_status", new[] { "Pending", "Assigned", "PickedUp", "InTransit", "Arrived", "Delivered", "Cancelled", "FailedDelivery" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "shipment_status", "shipment_status", new[] { "pending", "assigned", "picked_up", "in_transit", "arrived", "delivered", "cancelled", "failed_delivery" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "Customer", "Driver", "Admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", "user_role", new[] { "customer", "driver", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShipmentTrackingAPI.Models.CustomerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternatePhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("alternate_phone_number")
                        .HasComment("Backup contact number. Optional.");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number")
                        .HasComment("Primary customer contact. Visible to assigned driver.");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("profile_image_url")
                        .HasComment("Avatar URL. Store object in cloud storage; only the URL lives here.");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("customer_profiles_pkey");

                    b.HasIndex(new[] { "UserId" }, "uq_customer_profiles_user_id")
                        .IsUnique();

                    b.ToTable("customer_profiles", null, t =>
                        {
                            t.HasComment("1:1 vertical partition of users for Customer-specific data. Avoids NULLs on Driver and Admin rows.");
                        });
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.DriverProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DriverAccountStatus>("AccountStatus")
                        .HasColumnType("driver_account_status")
                        .HasColumnName("account_status");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer")
                        .HasColumnName("approved_by")
                        .HasComment("FK to users: the Admin who set account_status = Active.");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("CurrentLat")
                        .HasColumnType("double precision")
                        .HasColumnName("current_lat")
                        .HasComment("Live GPS latitude. Written by GpsSimulationService every 5s during InTransit.");

                    b.Property<double?>("CurrentLng")
                        .HasColumnType("double precision")
                        .HasColumnName("current_lng")
                        .HasComment("Live GPS longitude. Written by GpsSimulationService every 5s during InTransit.");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("license_number");

                    b.Property<DriverOpStatus?>("OpStatus")
                        .HasColumnType("driver_op_status")
                        .HasColumnName("op_status");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number")
                        .HasComment("Driver contact number. Shown to customer after assignment.");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vehicle_number")
                        .HasComment("Registration plate. e.g. TS-09-AB-1234. Customer verifies this at pickup.");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("Id")
                        .HasName("driver_profiles_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex(new[] { "LicenseNumber" }, "uq_driver_profiles_license")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "uq_driver_profiles_user_id")
                        .IsUnique();

                    b.ToTable("driver_profiles", null, t =>
                        {
                            t.HasComment("1:1 vertical partition of users for Driver-specific data. Avoids NULLs on Customer and Admin rows.");
                        });
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.SavedAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("address_line_2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id")
                        .HasComment("FK to customer_profiles.id — not users.id. Scoped to customer profile, not raw user.");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default")
                        .HasComment("At most one TRUE per customer. Enforced by uix_saved_addresses_one_default_per_customer.");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label")
                        .HasComment("User-friendly label: Home, Office, Parents, Warehouse, etc.");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("saved_addresses_pkey");

                    b.HasIndex(new[] { "CustomerId" }, "idx_saved_addresses_customer_id");

                    b.HasIndex(new[] { "CustomerId" }, "uix_saved_addresses_one_default_per_customer")
                        .IsUnique()
                        .HasFilter("(is_default = true)");

                    b.ToTable("saved_addresses", null, t =>
                        {
                            t.HasComment("Customer address book. Many saved addresses per customer_profile. One default enforced by partial unique index.");
                        });
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at")
                        .HasComment("Set when status transitions to Cancelled. NULL for all other statuses.");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id")
                        .HasComment("The Sender. NOT NULL — a shipment always has an owner.");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at")
                        .HasComment("Set when Delivery OTP is verified. Legal proof-of-delivery timestamp (POD).");

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id")
                        .HasComment("NULL until a driver self-assigns. ON DELETE SET NULL preserves history.");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at")
                        .HasComment("Set when status transitions to FailedDelivery. NULL for all other statuses.");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("picked_up_at")
                        .HasComment("Set when Pickup OTP is verified. Legal proof-of-pickup timestamp (POP).");

                    b.Property<ShipmentStatus>("Status")
                        .HasColumnType("shipment_status")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_cost");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tracking_number")
                        .HasComment("Public identifier. Format: TRK-XXXXXX. Generated by TrackingNumberService.");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("shipments_pkey");

                    b.HasIndex(new[] { "CustomerId" }, "idx_shipments_customer_id");

                    b.HasIndex(new[] { "DriverId" }, "idx_shipments_driver_id")
                        .HasFilter("(driver_id IS NOT NULL)");

                    b.HasIndex(new[] { "TrackingNumber" }, "uq_shipments_tracking_number")
                        .IsUnique();

                    b.ToTable("shipments", null, t =>
                        {
                            t.HasComment("Delivery contract. Addresses in shipment_addresses; OTP state in shipment_otp_windows.");
                        });
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.ShipmentAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line");

                    b.Property<AddressType>("AddressType")
                        .HasColumnType("address_type")
                        .HasColumnName("address_type");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contact_name")
                        .HasComment("NULL on Pickup (sender identified via customer_id). Required on Dropoff.");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone")
                        .HasComment("NULL on Pickup. Required on Dropoff — driver contacts recipient on arrival.");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id")
                        .HasName("shipment_addresses_pkey");

                    b.HasIndex(new[] { "ShipmentId" }, "idx_shipment_addresses_shipment_id");

                    b.ToTable("shipment_addresses", null, t =>
                        {
                            t.HasComment("Address rows per shipment. Replaces 8 pickup/dropoff/recipient columns on shipments.");
                        });
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.ShipmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id")
                        .HasComment("NULL = system/BackgroundService. Set to user ID for Driver, Customer, and Admin actions.");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude")
                        .HasComment("GPS snapshot at event time. Accumulates the breadcrumb trail.");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()")
                        .HasComment("Always ORDER BY occurred_at ASC for the tracking timeline.");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("shipment_id");

                    b.Property<ShipmentStatus>("Status")
                        .HasColumnType("shipment_status")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("shipment_events_pkey");

                    b.HasIndex("ActorId");

                    b.HasIndex(new[] { "ShipmentId" }, "idx_shipment_events_shipment_id");

                    b.ToTable("shipment_events", null, t =>
                        {
                            t.HasComment("Append-only audit log. Insert once per transition. Never update or delete rows.");
                        });
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.ShipmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("height_cm");

                    b.Property<decimal?>("LengthCm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("length_cm");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity")
                        .HasComment("Count of identical units of this item in the shipment.");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("shipment_id");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)")
                        .HasColumnName("weight_kg")
                        .HasComment("Weight per unit. Total shipment weight = SUM(weight_kg * quantity).");

                    b.Property<decimal?>("WidthCm")
                        .HasPrecision(6, 1)
                        .HasColumnType("numeric(6,1)")
                        .HasColumnName("width_cm");

                    b.HasKey("Id")
                        .HasName("shipment_items_pkey");

                    b.HasIndex(new[] { "ShipmentId" }, "idx_shipment_items_shipment_id");

                    b.ToTable("shipment_items", null, t =>
                        {
                            t.HasComment("1NF child table. One row per distinct item type per booking.");
                        });
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.ShipmentOtpWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AttemptCount")
                        .HasColumnType("smallint")
                        .HasColumnName("attempt_count")
                        .HasComment("Increments on wrong code. Reset to 0 on regeneration. Hard cap: 3.");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasComment("Audit: when the current code was issued or last regenerated.");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("otp_code")
                        .IsFixedLength()
                        .HasComment("NULL when no active window or after successful verification. Never exposed in views.");

                    b.Property<OtpType>("OtpType")
                        .HasColumnType("otp_type")
                        .HasColumnName("otp_type");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("integer")
                        .HasColumnName("shipment_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at")
                        .HasComment("Set on success. Never updated after. Permanent proof-of-verification record.");

                    b.HasKey("Id")
                        .HasName("shipment_otp_windows_pkey");

                    b.HasIndex(new[] { "ShipmentId" }, "idx_shipment_otp_shipment_id");

                    b.ToTable("shipment_otp_windows", null, t =>
                        {
                            t.HasComment("OTP state rows. Replaces 6 OTP columns on shipments. One row per type per shipment.");
                        });
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email")
                        .HasComment("citext: case-insensitive uniqueness. user@mail.com = USER@MAIL.COM.");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name")
                        .HasComment("Display name for all roles. Authoritative source — not duplicated in profile tables.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active")
                        .HasComment("Soft-delete flag. FALSE = account deactivated; all FK references preserved.");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash")
                        .HasComment("ASP.NET Core Identity PasswordHasher output. Never plain text.");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "uq_users_email")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Central identity for all roles. Single login endpoint, single FK target.");
                        });
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.CustomerProfile", b =>
                {
                    b.HasOne("ShipmentTrackingAPI.Models.User", "User")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("ShipmentTrackingAPI.Models.CustomerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_profiles_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.DriverProfile", b =>
                {
                    b.HasOne("ShipmentTrackingAPI.Models.User", "ApprovedByNavigation")
                        .WithMany("DriverProfileApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_driver_profiles_approved_by");

                    b.HasOne("ShipmentTrackingAPI.Models.User", "User")
                        .WithOne("DriverProfileUser")
                        .HasForeignKey("ShipmentTrackingAPI.Models.DriverProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_driver_profiles_user");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.SavedAddress", b =>
                {
                    b.HasOne("ShipmentTrackingAPI.Models.CustomerProfile", "Customer")
                        .WithMany("SavedAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_addresses_customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.Shipment", b =>
                {
                    b.HasOne("ShipmentTrackingAPI.Models.User", "Customer")
                        .WithMany("ShipmentCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_customer");

                    b.HasOne("ShipmentTrackingAPI.Models.User", "Driver")
                        .WithMany("ShipmentDrivers")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shipments_driver");

                    b.Navigation("Customer");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.ShipmentAddress", b =>
                {
                    b.HasOne("ShipmentTrackingAPI.Models.Shipment", "Shipment")
                        .WithMany("ShipmentAddresses")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_addresses_shipment");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.ShipmentEvent", b =>
                {
                    b.HasOne("ShipmentTrackingAPI.Models.User", "Actor")
                        .WithMany("ShipmentEvents")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shipment_events_actor");

                    b.HasOne("ShipmentTrackingAPI.Models.Shipment", "Shipment")
                        .WithMany("ShipmentEvents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_events_shipment");

                    b.Navigation("Actor");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.ShipmentItem", b =>
                {
                    b.HasOne("ShipmentTrackingAPI.Models.Shipment", "Shipment")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_items_shipment");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.ShipmentOtpWindow", b =>
                {
                    b.HasOne("ShipmentTrackingAPI.Models.Shipment", "Shipment")
                        .WithMany("ShipmentOtpWindows")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_otp_shipment");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.CustomerProfile", b =>
                {
                    b.Navigation("SavedAddresses");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.Shipment", b =>
                {
                    b.Navigation("ShipmentAddresses");

                    b.Navigation("ShipmentEvents");

                    b.Navigation("ShipmentItems");

                    b.Navigation("ShipmentOtpWindows");
                });

            modelBuilder.Entity("ShipmentTrackingAPI.Models.User", b =>
                {
                    b.Navigation("CustomerProfile");

                    b.Navigation("DriverProfileApprovedByNavigations");

                    b.Navigation("DriverProfileUser");

                    b.Navigation("ShipmentCustomers");

                    b.Navigation("ShipmentDrivers");

                    b.Navigation("ShipmentEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
