using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ShipmentTrackingAPI.Models.Enums;
using System.Text.Json.Serialization;
namespace ShipmentTrackingAPI.Models;

/// <summary>
/// Delivery contract. Addresses in shipment_addresses; OTP state in shipment_otp_windows.
/// </summary>
[Table("shipments")]
[Index("CustomerId", Name = "idx_shipments_customer_id")]
[Index("TrackingNumber", Name = "uq_shipments_tracking_number", IsUnique = true)]
public partial class Shipment
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// Public identifier. Format: TRK-XXXXXX. Generated by TrackingNumberService.
    /// </summary>
    [Column("tracking_number")]
    [StringLength(20)]
    public string TrackingNumber { get; set; } = null!;

    /// <summary>
    /// The Sender. NOT NULL — a shipment always has an owner.
    /// </summary>
    [Column("customer_id")]
    public int CustomerId { get; set; }

    /// <summary>
    /// NULL until a driver self-assigns. ON DELETE SET NULL preserves history.
    /// </summary>
    [Column("driver_id")]
    public int? DriverId { get; set; }
    [Column("status")]
    public ShipmentStatus Status { get; set; } = ShipmentStatus.Pending;

    [Column("total_cost",TypeName = "decimal(18,2)")]
    public decimal TotalCost { get; set; }
    /// <summary>
    /// Set when Pickup OTP is verified. Legal proof-of-pickup timestamp (POP).
    /// </summary>
    [Column("picked_up_at")]
    public DateTime? PickedUpAt { get; set; }

    /// <summary>
    /// Set when Delivery OTP is verified. Legal proof-of-delivery timestamp (POD).
    /// </summary>
    [Column("delivered_at")]
    public DateTime? DeliveredAt { get; set; }

    /// <summary>
    /// Set when status transitions to Cancelled. NULL for all other statuses.
    /// </summary>
    [Column("cancelled_at")]
    public DateTime? CancelledAt { get; set; }

    /// <summary>
    /// Set when status transitions to FailedDelivery. NULL for all other statuses.
    /// </summary>
    [Column("failed_at")]
    public DateTime? FailedAt { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Column("updated_at")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("ShipmentCustomers")]
    [JsonIgnore]
    public virtual User Customer { get; set; } = null!;

    [ForeignKey("DriverId")]
    [InverseProperty("ShipmentDrivers")]
    [JsonIgnore]
    public virtual User? Driver { get; set; }

    [InverseProperty("Shipment")]
    public virtual ICollection<ShipmentAddress> ShipmentAddresses { get; set; } = new List<ShipmentAddress>();

    [InverseProperty("Shipment")]
    public virtual ICollection<ShipmentEvent> ShipmentEvents { get; set; } = new List<ShipmentEvent>();

    [InverseProperty("Shipment")]
    public virtual ICollection<ShipmentItem> ShipmentItems { get; set; } = new List<ShipmentItem>();

    [InverseProperty("Shipment")]
    public virtual ICollection<ShipmentOtpWindow> ShipmentOtpWindows { get; set; } = new List<ShipmentOtpWindow>();
}
